{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "serviceexample.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.monitoring.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "serviceexample.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames: [ "{{ .Release.Namespace }}" ]
  endpoints:
    - port: {{ .Values.monitoring.serviceMonitor.port }}
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}


