apiVersion: v2
name: serviceexample
description: ServiceExample .NET API (MongoDB + Redis + NATS)
type: application
version: 0.1.1
appVersion: "0.1.0"
home: https://github.com/SathyaNarayanan-tut/mirasys-devops-assignment
sources:
  - https://github.com/SathyaNarayanan-tut/mirasys-devops-assignment
keywords:
  - dotnet
  - api
  - mongodb
  - redis
  - nats
maintainers:
  - name: Sathya Narayanan
    email: sathya.austin@gmail.com
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/SathyaNarayanan-tut/mirasys-devops-assignment

